### ISSUE TITLE
On create entry pages i.e timeline/task assignment/ etc. The edit button is visible and touchable when there are no entries

### ISSUE THREAD

**Issue by jhcarrington** [yuyanchua/ProgramPlanner#11]
Summary: Edit button should either not be visible or should not do anything when there are no entries in the list
Description: This functionality is confusing, because I can click edit and then the other buttons vanish
Severity: Low
Suggestions: Disable the button if the list length is 0

**Comment by yuyanchua** [comment]
The buttons are now hidden when the list is empty, updates on test branch
