### ISSUE TITLE
On delete entry i.e. task assignment/timeline/etc. there is no option to cancel your delete.

### ISSUE THREAD

**Issue by jhcarrington** [yuyanchua/ProgramPlanner#12]
Summary: When clicking delete there is only a confirm button. If you click on an entry and it is removed from the list, there is no way to cancel this action.
Description: ^
Severity: MEDIUM
Suggestions: Add a cancel button

**Comment by yuyanchua** [comment]
Add cancel button and confirmation dialog to cancel the delete action, updates on the test branch
