### ISSUE TITLE
Forgot password fields do not hide typed characters

### ISSUE THREAD

**Issue by ctfloyd** [yuyanchua/ProgramPlanner#16]
_Summary_
Ability to view typed password in a password field
_Description_
When going through the standard forgot password path, while you are typing your new password you are able to view the characters that you typed.
_Severity_
Medium
_Suggestion_
Hide the password characters as the user is typing, but perhaps give them the ability to view the typed characters using a button.

**Comment by xiangbbl** [comment]
Hidden fields added.
