### ISSUE TITLE
Adding an event to the timeline allows you to select a date in the past

### ISSUE THREAD

**Issue by ctfloyd** [yuyanchua/ProgramPlanner#18]
_Summary_
Ability to select a date in the past
_Description_
When adding a task to the timeline, you are allowed to select a date in the past and add an event on that day.
_Severity_
Low
_Suggestion_
This may be an intended feature especially because deadlines can be missed, but maybe the user should be warned when this happens. More often than not, when scheduling things, the user should be creating events in the future and having an event in the past may be a mistake that could be detected on behalf of the user.

**Comment by xiangbbl** [comment]
Unable to choose a data from past
