### ISSUE TITLE
Remove members is visible when no members are added to task assignment

### ISSUE THREAD

**Issue by cwangerin** [yuyanchua/ProgramPlanner#20]
_Summary_: Remove members button should either not be visible or should not do anything when there are no members in the list
_Description:_ This functionality is confusing, because I can click remove members and it gets rid of all the other buttons
_Severity_: Low
_Suggestions_: Disable the button and add warning text if the list length is 0

**Comment by xiangbbl** [comment]
When there are no members in the team member list, remove members button will do nothing and give a Toast at the same time.
