### ISSUE TITLE
Password Reset On Sign UP

### ISSUE THREAD

**Issue by mdmurphy2** [yuyanchua/ProgramPlanner#6]
After pressing foorgot password, then going back to sign up after creating your account it will ask you for security questions.

To Replicate:
Press forgot password, type in a username that does not exist.
Sign up with new credentials
Password reset will appear after signing up

**Comment by mdmurphy2** [comment]
After creating a project, and inviting others, the "reset password" page also appears. I am assuming something is being stored that is telling you that they are still in the "change password" state and never getting reset on exit.

**Comment by mdmurphy2** [comment]
Summary: Forgot Password Page is broken
Description: After pressing forgot password, then going back to sign up after creating your account it will ask you for security questions.
Severity: Medium
Suggestions: Likely some state is not getting updated if the forget password form is not completed

**Comment by yuyanchua** [comment]
Set return to main activity if member exit the reset password page, updates on the test branches
