### ISSUE TITLE
Kicking Members Does not give warning

### ISSUE THREAD

**Issue by mdmurphy2** [yuyanchua/ProgramPlanner#9]
Summary: When kicking a member it is easy to accidentally kick a member because there is no UI or warning
Description: after pressing kick member any member you click is automatically kicked with no warning
Severity: HIGH
Suggestions: Either give a pop up, or show that they are in "kick mode"

**Comment by mdmurphy2** [comment]
Correction: It does allow you to click kick members again, but I would just suggest making the UI more intuitive that you are in "kick mode" and perhaps select members you want to kick with check boxes (Change severity from high to medium)

**Comment by yuyanchua** [comment]
Added confirmation dialog before confirm member kick, updates on the test branch
